services:
  zaino-bot:
    build: .
    container_name: zaino-telegram-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./.trigger:/trigger
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
